"use client";
//import "./globals.css";
import { Inter } from "next/font/google";
import { createTheme, CssBaseline, ThemeProvider } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeDark = createTheme({
  palette: {
    //mode: "dark",
    background: {
      default: "#0d1116",
    },
    primary: {
      // light: will be calculated from palette.primary.main,
      main: "#0ca581",
      // dark: will be calculated from palette.primary.main,
      // contrastText: will be calculated to contrast with palette.primary.main
    },
    secondary: {
      //light: "#f5ee84",
      main: "#161c23",
      //dark: "#460370",
      // dark: will be calculated from palette.secondary.main,
      //contrastText: "#ffcc00",
    },
    // Used by `getContrastText()` to maximize the contrast between
    // the background and the text.
    contrastThreshold: 3,
    // Used by the functions below to shift a color's luminance by approximately
    // two indexes within its tonal palette.
    // E.g., shift from Red 500 to Red 300 or Red 700.
    tonalOffset: 0.2,
    text: {
      primary: "#000",
      secondary: "#fff",
    },
  },
  typography: {
    fontFamily: [
      "Raleway",
      "Arial",
      "sans-serif",
    ].join(","),
  },
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={themeDark}>
          <CssBaseline />

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
